const PDFDocument = require('pdfkit');

function line(doc, label, value) {
  doc.fillColor('#64748B').fontSize(9).text(label.toUpperCase());
  doc
    .fillColor('#111827')
    .fontSize(13)
    .text(value || 'Not provided');
  doc.moveDown(0.7);
}

function createDocument(title, booking = {}, sections = []) {
  const doc = new PDFDocument({ margin: 48 });
  doc.fillColor('#C45A19').fontSize(13).text('iTruck Africa', { continued: true });
  doc.fillColor('#64748B').text('  Freight Documents');
  doc.moveDown(1.2);
  doc.fillColor('#111827').fontSize(26).text(title);
  doc.moveDown();
  line(doc, 'Reference', booking.id || booking.bookingId);
  line(doc, 'Route', booking.route || 'Nairobi to Kampala');
  line(doc, 'Cargo', booking.cargo || 'General cargo');
  line(doc, 'Generated', new Date().toISOString());
  doc.moveDown();
  sections.forEach((section) => {
    doc.fillColor('#111827').fontSize(16).text(section.heading);
    doc.moveDown(0.4);
    section.items.forEach((item) => line(doc, item[0], item[1]));
    doc.moveDown(0.6);
  });
  doc
    .fillColor('#64748B')
    .fontSize(9)
    .text(
      'This document was generated by iTruck for shipment record keeping. Verify all details before regulatory or customs submission.',
      { align: 'left' }
    );
  doc.end();
  return doc;
}

function toBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

function createWaybill(booking) {
  return createDocument('Waybill', booking, [
    {
      heading: 'Transport Details',
      items: [
        ['Pickup', booking.pickup || 'Nairobi'],
        ['Destination', booking.destination || 'Kampala'],
        ['Vehicle', booking.vehicle || 'Lorry'],
        ['Driver', booking.driver || 'James Mwangi']
      ]
    },
    {
      heading: 'Consignment',
      items: [
        ['Weight', booking.weight || '12 tonnes'],
        ['Packaging', booking.packaging || 'Sealed pallets'],
        ['Special instructions', booking.instructions || 'Handle with care']
      ]
    }
  ]);
}

function createPOD(booking) {
  return createDocument('Proof of Delivery', booking, [
    {
      heading: 'Delivery Confirmation',
      items: [
        ['Delivered to', booking.receiver || 'Receiving officer'],
        ['Delivery time', booking.deliveredAt || new Date().toISOString()],
        ['Condition', booking.condition || 'Received in good condition'],
        ['Confirmed by', booking.confirmedBy || 'Client representative']
      ]
    },
    {
      heading: 'Evidence',
      items: [
        ['GPS trail', 'Available in tracking history'],
        ['Photos', 'Cargo photos attached in shipment record'],
        ['Signature', 'Digital confirmation recorded']
      ]
    }
  ]);
}

function createInvoice(booking) {
  return createDocument('Commercial Invoice', booking, [
    {
      heading: 'Billing',
      items: [
        ['Client', booking.client || 'Client account'],
        ['Owner', booking.owner || 'Fleet owner'],
        ['Base freight', booking.base || '$920'],
        ['Escrow/payment status', booking.paymentStatus || 'Paid']
      ]
    },
    {
      heading: 'Charges',
      items: [
        ['Insurance', booking.insurance || '$32'],
        ['Platform fee', booking.platformFee || '$23'],
        ['Total', booking.total || '$975']
      ]
    }
  ]);
}

function createCustoms(booking) {
  return createDocument('Cross-Border Customs Summary', booking, [
    {
      heading: 'Border Information',
      items: [
        ['Origin country', booking.originCountry || 'Kenya'],
        ['Destination country', booking.destinationCountry || 'Uganda'],
        ['Border point', booking.borderPoint || 'Busia'],
        ['Declaration status', booking.declarationStatus || 'Draft']
      ]
    },
    {
      heading: 'Cargo Declaration',
      items: [
        ['Commodity', booking.cargo || 'General cargo'],
        ['Declared value', booking.declaredValue || '$8,500'],
        ['HS code', booking.hsCode || 'To be confirmed']
      ]
    }
  ]);
}

module.exports = { createWaybill, createPOD, createInvoice, createCustoms, toBuffer };
