const PDFDocument = require('pdfkit');

const DOCUMENT_COLORS = {
  brand: '#06402B',
  ink: '#07251A',
  muted: '#5F7168'
};

function line(doc, label, value) {
  doc.fillColor(DOCUMENT_COLORS.muted).fontSize(9).text(label.toUpperCase());
  doc
    .fillColor(DOCUMENT_COLORS.ink)
    .fontSize(13)
    .text(value || 'Not provided');
  doc.moveDown(0.7);
}

function createDocument(title, booking = {}, sections = []) {
  const doc = new PDFDocument({ margin: 48 });
  doc.fillColor(DOCUMENT_COLORS.brand).fontSize(13).text('iTruck Africa', { continued: true });
  doc.fillColor(DOCUMENT_COLORS.muted).text('  Freight Documents');
  doc.moveDown(1.2);
  doc.fillColor(DOCUMENT_COLORS.ink).fontSize(26).text(title);
  doc.moveDown();
  line(doc, 'Reference', booking.id || booking.bookingId);
  line(doc, 'Route', booking.route || 'Nairobi to Kampala');
  line(doc, 'Cargo', booking.cargo || 'General cargo');
  line(doc, 'Generated', new Date().toISOString());
  doc.moveDown();
  sections.forEach((section) => {
    doc.fillColor(DOCUMENT_COLORS.ink).fontSize(16).text(section.heading);
    doc.moveDown(0.4);
    section.items.forEach((item) => line(doc, item[0], item[1]));
    doc.moveDown(0.6);
  });
  doc
    .fillColor(DOCUMENT_COLORS.muted)
    .fontSize(9)
    .text(
      'This document was generated by iTruck for shipment record keeping. Verify all details before regulatory or customs submission.',
      { align: 'left' }
    );
  doc.end();
  return doc;
}

function toBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

function createWaybill(booking) {
  return createDocument('Waybill', booking, [
    {
      heading: 'Transport Details',
      items: [
        ['Pickup', booking.pickup || 'Nairobi'],
        ['Destination', booking.destination || 'Kampala'],
        ['Vehicle', booking.vehicle || 'Lorry'],
        ['Driver', booking.driver || 'Assigned driver']
      ]
    },
    {
      heading: 'Consignment',
      items: [
        ['Weight', booking.weight || '12 tonnes'],
        ['Packaging', booking.packaging || 'Sealed pallets'],
        ['Special instructions', booking.instructions || 'Handle with care']
      ]
    }
  ]);
}

function createPOD(booking) {
  return createDocument('Proof of Delivery', booking, [
    {
      heading: 'Delivery Confirmation',
      items: [
        ['Delivered to', booking.receiver || 'Receiving officer'],
        ['Delivery time', booking.deliveredAt || new Date().toISOString()],
        ['Condition', booking.condition || 'Received in good condition'],
        ['Confirmed by', booking.confirmedBy || 'Client representative']
      ]
    },
    {
      heading: 'Evidence',
      items: [
        ['GPS trail', 'Available in tracking history'],
        ['Photos', 'Cargo photos attached in shipment record'],
        ['Signature', 'Digital confirmation recorded']
      ]
    }
  ]);
}

function createReceiverConfirmation(booking) {
  return createDocument('Receiver Confirmation', booking, [
    {
      heading: 'Receiver',
      items: [
        ['Receiver name', booking.receiverName || booking.receiver || 'Receiving officer'],
        ['Receiver phone', booking.receiverPhone || 'Not provided'],
        ['Destination', booking.destination || 'Delivery destination'],
        ['Expected handover', booking.pickupWindow || booking.deliveredAt || 'To be confirmed']
      ]
    },
    {
      heading: 'Acknowledgement',
      items: [
        ['Cargo', booking.cargo || 'General cargo'],
        ['Condition', booking.condition || 'To be confirmed at delivery'],
        ['Confirmation method', booking.communicationPreference || 'Digital confirmation'],
        ['Signature', 'Pending receiver signature']
      ]
    }
  ]);
}

function createInvoice(booking) {
  return createDocument('Commercial Invoice', booking, [
    {
      heading: 'Billing',
      items: [
        ['Client', booking.client || 'Client account'],
        ['Owner', booking.owner || 'Fleet owner'],
        ['Base freight', booking.base || '$920'],
        ['Escrow/payment status', booking.paymentStatus || 'Paid']
      ]
    },
    {
      heading: 'Charges',
      items: [
        ['Insurance', booking.insurance || '$32'],
        ['Platform fee', booking.platformFee || '$23'],
        ['Total', booking.total || '$975']
      ]
    }
  ]);
}

function createPackingList(booking) {
  return createDocument('Packing List', booking, [
    {
      heading: 'Cargo Package',
      items: [
        ['Cargo', booking.cargo || 'General cargo'],
        ['Weight', booking.weight || 'Not provided'],
        ['Handling', booking.requirements || 'Standard'],
        ['Packaging', booking.packaging || 'To be confirmed']
      ]
    },
    {
      heading: 'Shipment',
      items: [
        ['Pickup', booking.pickup || 'Pickup pending'],
        ['Destination', booking.destination || 'Destination pending'],
        ['Vehicle type', booking.vehicleType || booking.vehicle || 'Vehicle pending'],
        ['Cargo value', booking.cargoValue || booking.declaredValue || 'Not declared']
      ]
    }
  ]);
}

function createCustoms(booking) {
  return createDocument('Cross-Border Customs Summary', booking, [
    {
      heading: 'Border Information',
      items: [
        ['Origin country', booking.originCountry || 'Kenya'],
        ['Destination country', booking.destinationCountry || 'Uganda'],
        ['Border point', booking.borderPoint || 'Busia'],
        ['Declaration status', booking.declarationStatus || 'Draft']
      ]
    },
    {
      heading: 'Cargo Declaration',
      items: [
        ['Commodity', booking.cargo || 'General cargo'],
        ['Declared value', booking.declaredValue || '$8,500'],
        ['HS code', booking.hsCode || 'To be confirmed']
      ]
    }
  ]);
}

function createCargoValueDeclaration(booking) {
  return createDocument('Cargo Value Declaration', booking, [
    {
      heading: 'Declared Cargo Value',
      items: [
        ['Cargo', booking.cargo || 'General cargo'],
        ['Declared value', booking.cargoValue || booking.declaredValue || 'Not declared'],
        ['Currency', booking.currency || 'USD'],
        ['Insurance basis', booking.insuranceBasis || 'Declared by shipper']
      ]
    },
    {
      heading: 'Handover Notes',
      items: [
        ['Pickup', booking.pickup || 'Pickup pending'],
        ['Destination', booking.destination || 'Destination pending'],
        ['Receiver', booking.receiverName || booking.receiver || 'Receiver pending'],
        ['Condition exceptions', booking.conditionExceptions || 'None recorded']
      ]
    }
  ]);
}

module.exports = {
  createWaybill,
  createPOD,
  createReceiverConfirmation,
  createInvoice,
  createPackingList,
  createCustoms,
  createCargoValueDeclaration,
  toBuffer
};
