export const demoFleet = [
  {
    id: 'KDA-442Q',
    type: 'Lorry',
    name: 'Isuzu FVZ 34',
    plate: 'KDA 442Q',
    owner: 'James Mwangi',
    company: 'Mwangi Haulage',
    price: '$2.10/km',
    pricePerKm: 2.1,
    capacity: '12 tonnes',
    rating: 4.8,
    ratingCount: 146,
    trips: 146,
    photos: ['https://www.kentrucksisuzu.com/uploads/img/pages/isuzu-fvz34t-truck.webp'],
    routeFit: 94,
    availability: 'Available today',
    documentStatus: 'Docs verified',
    responseTime: '< 10 min',
    routes: ['Nairobi-Kampala', 'Mombasa-Nairobi'],
    features: ['GPS', 'Insured', 'Cross-border'],
    verified: true
  },
  {
    id: 'KCB-991T',
    type: 'Trailer',
    name: 'Scania R450',
    plate: 'KCB 991T',
    owner: 'Grace Wanjiku',
    company: 'Wanjiku Logistics',
    price: '$3.80/km',
    pricePerKm: 3.8,
    capacity: '28 tonnes',
    rating: 4.9,
    ratingCount: 211,
    trips: 211,
    photos: ['https://commons.wikimedia.org/wiki/Special:FilePath/Scania_truck_R_450,_FreshLinc.JPG'],
    routeFit: 91,
    availability: 'Available tomorrow',
    documentStatus: 'Docs verified',
    responseTime: '< 15 min',
    routes: ['Nairobi-Lagos', 'Mombasa-Kigali'],
    features: ['GPS', 'Container locks', 'Long haul'],
    verified: true
  },
  {
    id: 'LAG-882B',
    type: 'Bus',
    name: 'Yutong ZK6122',
    plate: 'LAG 882B',
    owner: 'Tunde Logistics',
    company: 'Tunde Logistics',
    price: '$1.90/km',
    pricePerKm: 1.9,
    capacity: 'Mixed cargo / passenger',
    rating: 4.4,
    ratingCount: 73,
    trips: 73,
    photos: ['https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=900&q=80'],
    routeFit: 72,
    availability: 'Manual confirmation',
    documentStatus: 'Docs pending',
    responseTime: 'Manual review',
    routes: ['Lagos-Abuja', 'Lagos-Accra'],
    features: ['Passenger permits', 'Parcel hold'],
    verified: false
  },
  {
    id: 'KDG-128P',
    type: 'Pickup',
    name: 'Toyota Hilux',
    plate: 'KDG 128P',
    owner: 'Amina Osei',
    company: 'Amina Express',
    price: '$1.25/km',
    pricePerKm: 1.25,
    capacity: '1.2 tonnes',
    rating: 4.7,
    ratingCount: 89,
    trips: 89,
    photos: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80'],
    routeFit: 88,
    availability: 'Available now',
    documentStatus: 'Docs verified',
    responseTime: '< 20 min',
    routes: ['Accra-Kumasi', 'Tema-Accra'],
    features: ['Rural roads', 'Express', 'Small cargo'],
    verified: true
  }
];

export const demoShipments = [
  {
    id: 'ITK-2044',
    route: 'Nairobi to Kampala',
    origin: 'Nairobi',
    destination: 'Kampala',
    cargo: 'Retail stock',
    vehicle: 'Isuzu FVZ 34',
    plate: 'KDA 442Q',
    driver: 'Daniel Otieno',
    status: 'In transit',
    progress: 64,
    eta: 'Today 18:40',
    position: 'Near Nakuru',
    speed: '72 km/h',
    payment: 'Escrow held',
    documents: ['Waybill ready', 'Cargo photos shared', 'POD pending']
  },
  {
    id: 'ITK-2031',
    route: 'Mombasa to Dar es Salaam',
    origin: 'Mombasa',
    destination: 'Dar es Salaam',
    cargo: 'Machine parts',
    vehicle: 'Scania R450',
    plate: 'KCB 991T',
    driver: 'Peter Mwangi',
    status: 'Bids open',
    progress: 18,
    eta: '3 bids received',
    position: 'Awaiting award',
    speed: 'Pending dispatch',
    payment: 'Budget pending',
    documents: ['Commercial invoice needed', 'Packing list needed']
  },
  {
    id: 'ITK-2028',
    route: 'Accra to Lagos',
    origin: 'Accra',
    destination: 'Lagos',
    cargo: 'Packaged food',
    vehicle: 'Toyota Hilux',
    plate: 'KDG 128P',
    driver: 'Kwame Mensah',
    status: 'Delivered',
    progress: 100,
    eta: 'POD ready',
    position: 'Lagos warehouse',
    speed: 'Complete',
    payment: 'Release ready',
    documents: ['POD ready', 'Invoice ready']
  }
];

export const demoLoads = [
  { cargo: 'Maize bags', route: 'Kampala to Mombasa', price: 1850, distance: '1,140 km', window: 'Pickup tomorrow', fit: '92% fit', risk: 'Medium' },
  { cargo: 'Construction steel', route: 'Nairobi to Kigali', price: 2400, distance: '1,170 km', window: 'Bids close in 2h', fit: '88% fit', risk: 'Medium' },
  { cargo: 'Cold chain produce', route: 'Arusha to Dar es Salaam', price: 980, distance: '630 km', window: 'Needs refrigerated truck', fit: '76% fit', risk: 'High' }
];

export const demoDocuments = ['Waybill', 'Cargo photos', 'Receiver confirmation', 'Commercial invoice', 'Packing list', 'Customs declaration'];
