window.iTruckShipments = [
  {
    id: 'ITK-2044',
    route: 'Nairobi to Kampala',
    origin: 'Nairobi, Kenya',
    destination: 'Kampala, Uganda',
    progress: 64,
    position: 'Near Nakuru',
    speed: '72 km/h',
    eta: '8h 20m',
    driver: 'James Mwangi',
    phone: '+254711000000',
    whatsapp: '+254711000000',
    email: 'james@itruck.africa',
    cargo: 'Retail stock',
    vehicle: 'Isuzu FVZ 34',
    plate: 'KDA 442Q',
    contactPreference: 'WhatsApp first, phone for urgent updates',
    contactWindow: '06:00 - 21:00 EAT',
    contactChoices: { phone: true, whatsapp: true, email: true, chat: true }
  },
  {
    id: 'ITK-1988',
    route: 'Accra to Lagos',
    origin: 'Accra, Ghana',
    destination: 'Lagos, Nigeria',
    progress: 42,
    position: 'Near Lome',
    speed: '61 km/h',
    eta: '14h 10m',
    driver: 'Kojo Mensah',
    phone: '+233200000000',
    whatsapp: '+233200000000',
    email: 'kojo.mensah@itruck.africa',
    cargo: 'Packaged goods',
    vehicle: 'Yutong ZK6122',
    plate: 'LAG 882B',
    contactPreference: 'In-app chat for routine updates, call for route issues',
    contactWindow: '07:00 - 20:00 GMT',
    contactChoices: { phone: true, whatsapp: true, email: true, chat: true }
  },
  {
    id: 'ITK-2077',
    route: 'Mombasa to Kigali',
    origin: 'Mombasa, Kenya',
    destination: 'Kigali, Rwanda',
    progress: 22,
    position: 'Outside Voi',
    speed: '68 km/h',
    eta: '1d 6h',
    driver: 'Grace Wanjiku',
    phone: '+254722000000',
    whatsapp: '',
    email: 'grace@itruck.africa',
    cargo: 'Machine parts',
    vehicle: 'Scania R450',
    plate: 'KCB 991T',
    contactPreference: 'Email for documents, phone for pickup or delivery changes',
    contactWindow: '08:00 - 18:00 EAT',
    contactChoices: { phone: true, whatsapp: false, email: true, chat: true }
  }
];
